on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: torisetsu
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          distribution: 'adopt'
      - name: grant execute permission for gradlew
        run: chmod +x gradlew
      - name: build
        run: |
          ./gradlew build

      - uses: actions/checkout@v4
      - name: Check file existence
        id: check_files
        working-directory: torisetsu/build/dist/js/productionExecutable
        uses: andstor/file-existence-action@v3
        with:
          files: "index.html, torisetsu.js"
      - name: File exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: echo All files exists!
