on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: torisetsu
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          distribution: 'adopt'
      - name: grant execute permission for gradlew
        run: chmod +x gradlew
      - name: build
        run: |
          ./gradlew jsBrowserProductionWebpack
          cp build/kotlin-webpack/js/productionExecutable/* build/processedResources/js/main/
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: github-pages
          FOLDER: torisetsu/build/processedResources/js/main
          CLEAN: true
